### ISSUE TITLE
How to convert model?

### ISSUE THREAD

**Issue by sivikee** [surendramaran/YOLOv8-TfLite-Object-Detector#3]
Hello!
Thanks for this app!
Can you tell me how can i convert my pt or onnx to tflite?
I followed some guides, but and i get a float16 and float32 model but neither wants to work.

**Comment by sivikee** [comment]
I managed to start it, its just extremely slow. Any suggestions maybe?

**Comment by surendramaran** [comment]
The performance is highly depends on the device. Android devices have limited resources that's why Tensorflow specifically made tflite for such devices. It's recommended to use tflite not protobufer for Android, iOS, or raspberry pi.

You should train your model in 320x320 or 256x256 or 216x216 image resolution. Secondly you should use int8 quantised tflite model.

Lastly use YOLOv8n only for mobile devices

**Comment by surendramaran** [comment]
For converting .pt to .tflite

Use
"yolo export model=my_model.pt format=tflite imgsz=320 int8=true"

**Comment by sivikee** [comment]
Thanks for answering i was missing the int8=true part

**Comment by sandeepmassey** [comment]
Hello.
Thanks for your very nice app. 
I successfully converted yolov8n.pt to .tflite with following code:

from ultralytics import YOLO

model = YOLO("F:\\Yolo\\yolov8\\yolov8n.pt")
model.export(format='tflite', imgsz=320, int8=True)

The saved .tflite files are:  yolov8n_float16.tflite, yolov8n_float32.tflite, yolov8n_full_integer_quant.tflite, yolov8n_int8.tflite, yolov8n_integer_quant.tflite

I wish to run this app on an Android device. Could you please suggest which of the above model files should I use. Also what should I choose for INPUT_IMAGE_TYPE and OUTPUT_IMAGE_TYPE, -> DataType.FLOAT32 or DataType.UINT8.

Thanks.

**Comment by surendramaran** [comment]
Float 32 you can run for now, I haven't successfully run uint8 model yet
