### ISSUE TITLE
Bounding box

### ISSUE THREAD

**Issue by DuckonFire** [surendramaran/YOLOv8-TfLite-Object-Detector#8]
How to remove the bounding box after detection? Ex: bounding box gone after 1s
When i try this code bounding box doesnt gove even after no item to detect.

Oh and how to also show the confidence score on the bounding box

**Comment by sampm092** [comment]
I got the same issue too.. I don't really understand kotlin, i tried to analyze the bestbox function and applyNMS function but i don't really know which part will make the difference

I'll wait for the exact answer

**Comment by surendramaran** [comment]
@DuckonFire  I didn't pay attention and called a different function.

instead of calling 
binding.overlay.clear()

I called
binding.overlay.invalidate()

So it fixed the problem. Kindly check the updated code.

And regarding the confidence score, you can get that in MainActivity.kt file

look for onDetect listener. boundingBoxes will have the confidence scores of detection objects.

**Comment by sampm092** [comment]
Thanks @surendramaran my only issue is that bounding box and it's solved
